FROM node:12.7-alpine AS build
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install
COPY . .
RUN npm run build


### STAGE 2: Run ###
FROM nginx:1.17.1-alpine
RUN apk add nano && apk add curl
COPY --from=build /usr/src/public /usr/share/nginx/html
